#' find_changepoints
#'
#' Returns the position of changepoints in the sequence
#'
#' @param sequence A vector of floats
#' @param minimum_distance The minimum distance between changepoints as percentage of sequence length
#' @param process_count The different amount of processes generating data in the sequence. For example if a sequence is generated by alternating processes like this: A B A B A B then the changepoint count might be 5 but the process count is 2
#'
#' @return The list of changepoints in increasing size
#'
#' @export
find_changepoints <- function(sequence, minimum_distance, process_count) {
  PyChest <- reticulate::import("PyChest")
  PyChest$find_changepoints(sequence, minimum_distance, process_count)
}
